# Default values for httpbin.
# This is a YAML-formatted file.

# The overall system your service is a part of
system: httpbin
# The name of your service
service: httpbin
# The major version number for your service
version: 1

# Istio uses the service account name as a component of the service's security
# identity. Set "create" to false to use an previously created service account.
serviceAccount:
  name: httpbin
  create: true

# The number of pod replicas to run for your service
replicaCount: 1
# The maximum number of pods from that set that can be unavailable at once
maxUnavailable: 1

# Docker settings
image:
  # The name of your docker container
  repository: docker.io/kennethreitz/httpbin
  # Your docker container's tag
  tag: latest
  imagePullPolicy: IfNotPresent

# Port settings
# Ports must be named <protocol>[-<suffix>] to work with Istio.
# Valid protocols are grpc, http, http2, https, mongo, mysql, redis, tcp, tls, udp
ports:
  - name: http
    port: 80
    targetPort: 80

# Configure the Istio ingress gateway to route outside traffic for the provided
# host name to this service on the ports and protocols defined in the 'ports' section 
# above. 
ingressGateway:
  name: default/istio-gateway
  host: lvh.me
  matchPrefix: 
    - "/delete"
    - "/get"
    - "/patch"
    - "/post"
    - "/put"
    - "/status"

# Resource settings (use Kubernetes syntax)
resources:
  requests:
    memory: "32Mi"
    cpu: "200m"
  limits:
    memory: "64Mi"
    cpu: "250M"

# Probe settings (use Kubernetes syntax)
probes:
  livenessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /status/200
      port: 80
  readinessProbe:
    timeoutSeconds: 10
    httpGet:
      path: /status/200
      port: 80
