namespacePolicy:
  defaultDeny: true
  mtlsMode: STRICT

authorizations:
  myService:
    matchLabels:
      app: myService
    rules:
    - allowPrincipals:
      - namespace/serviceAccount
      paths:
      - /*
