namespacePolicy:
  default:
    defaultDeny: true
    mtlsMode: STRICT

authorizations:
  myService:
    enabled: true
    namespace: default
    matchLabels:
      app: myService
    rules:
    - allowPrincipals:
      - namespace/serviceAccount
      paths:
      - /*
