{{- range $key, $spec := .Values.namespacePolicy }}
{{- if $spec.defaultDeny }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "default-authorization-policy"
  namespace: {{ $key | quote }}
spec:
  {}
{{- else }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "default-authorization-policy"
  namespace: {{ $key | quote }}
spec:
  action: ALLOW
  rules:
  - {}
{{- end }}
---
{{- end }}